apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: example-webhook
webhooks:
  - name: example-webhook.default.svc.cluster.local
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 30
    objectSelector:
      matchLabels:
        example-webhook-enabled: "true"
    clientConfig:
      service:
        name: example-webhook
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkRENDQWx5Z0F3SUJBZ0lVS3MwUDM5aVBJekZhZERzMm1GVEdyZ0xnNHF3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qSXdOakUwCk1UVTBOekF3V2hjTk1qY3dOakV6TVRVME56QXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOQXJKL1BxCmJ6N3NsNGJpRXNZNnhsc1hvcERHUlBEM1lJWE5TZTVwSUkrQ3NGZjJ5Y1JSTTJrM2NubjdGWU1UNGlDdmh2ZGQKNk5BTTRhSWhXVnhmMm5IaC80OUpxWUlMcmJnZ0pMWFdVeG4weE8razM3WkMvbVRpN3IvbWJsLzhYSEVHbHBNSwo2eWtPRXVKcmtDc29JN1czeUtLUEZIRHM4N2xoVWNQS1dzOHRRQjVLOE5uVFZuQS85TzJHdWEza2RBY2xGOVo1CjQzKzZjbXgwSmVNeDdwK1lVTTFLcFNucEVBZmJVY0JSMmRwcDd1WmFQdk5tVldkbnpxTlVVZ1lPQ3FPOW8vczQKWk1UQ0R6ajA1Z2lMT2ZsbVdrQW1taEpEV3k2SlRIbTRzUmNHRUtoeHVzT091bi83N1FtRG10WlZ5cE9rbzJwTQpWYUd0VjZwT3BSeTM3bXNDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGCk1BTUJBZjh3SFFZRFZSME9CQllFRlA1UmZUSU0yRDZRRVp2blF6T0YxMnpJWktMTk1BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUI0dTdxRFhkeU5DK2ZvTHZTNzB6RTVTN0xlOHRjY0p4aGJLMHBDTU1GWHkwMTN5L21ZYkNIVApKZzRnTFNQK0FCOG92VThLQlN1SlZ2b3V2eURyZXgyNmpoSEVBZmhVNVFMemI5ZHFrOGc1YXZxRjl0Szl6VGNjCjY0d2h6NTBScC9ZUGhlbTFhUVpZbWdDTjlQTzB3WTN4RU1UUlpwWXUzeHNZOWd1ZFhhV0xNZStPdnJoU04wdFYKLzJSemU2VytMeExaNUNEbkxqK1p6YlVydW5FcWRRTW9VYnBPTmZnaEJFTVpoMDltVkp2emxHNkYwMldxb053NQp3V1NNd2REanFZM1NTRkpmSWpFdXBlUHR0UEthYU0yU0lpUk1ENSs4ZkJoRFhnOENSeTk5QU42QUVuSThGSFIrCjRXQWFoMnc5OVhCb1JxR0FhdDEzUTkyREFvd0hWSjIxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]